#cloud-config
repo_update: true
repo_upgrade: false
apt_reboot_if_required: true

timezone: UTC

final_message: "System boot (via cloud-init) is COMPLETE, after $UPTIME seconds."

runcmd:
 - export AWS_ACCESS_KEY_ID=${access_key}
 - export AWS_SECRET_ACCESS_KEY=${secret_key}
 - export AWS_DEFAULT_REGION=${region}
 - mkdir /root/.aws && echo "[default]" > /root/.aws/credentials && echo "aws_access_key_id = ${access_key}" >> /root/.aws/credentials && echo "aws_secret_access_key = ${secret_key}" >> /root/.aws/credentials 
 - yum install -y openjdk-8-jdk java-1.8.0-openjdk-devel.x86_64 git python-pip gcc libstdc++-devel gcc-c++ curl-devel libxml2-devel
 - mkdir -p /var/www
 - cd /var/www && git clone https://github.com/scm-spain/devops-test-helloworld-app.git && cd devops-test-helloworld-app
 - sed -i 's/\(^.*password:.*$\)/\1 d1g1t4ln0c-/' src/main/resources/application-pro.yml
 - sed -i "s/helloworld.database.lan:5432/${bbdd_address}/" src/main/resources/application-pro.yml
 - ./gradlew build
 - java -jar build/libs/helloworld-0.0.1-SNAPSHOT.jar --spring.profiles.active=pro &
 - pip install awscli
 - pip install ec2-metadata
 - INSTANCE_ID=$(ec2-metadata --instance-id |awk '{ print $2 }')
 - crontab -l | { /bin/cat; echo "* * * * * /bin/aws s3 cp /var/log/hello-world/app.log s3://helloworldtest-logs/app-$INSTANCE_ID.log"; } | crontab -

output:
  all: '| tee -a /var/log/cloud-init-output.log'
